### ISSUE TITLE
[feature request] add original single player game

### ISSUE THREAD

**Issue by legluondunet** [mvdevs/jk2mv#106]
Hello jk2mv dev team,
actually on Linux (and other platforms) we have choice between OpenJK and XLava port to play the original JKO II single player game.
But this ports are not as advanced as jk2mv:
- no HD resolution 1920x1080 or better, no ratio, no fov (https://github.com/JACoders/OpenJK/issues/958)
- no EAX support (https://github.com/JACoders/OpenJK/issues/285)
- Cinematics does not play correctly, sound is noisy, this is bad for immersion (https://github.com/JACoders/OpenJK/issues/897)

jk2mv project already has all this features need by modern computer and more than that like dynamic glow etc...
Is it a big task or jk2mv has already the engine and other features to implement it?
Is it in your TODO list?

**Comment by ouned** [comment]
You can use a custom resolution r_mode -1 and r_customwidth/height.

It's easier and faster to fix the remaining bugs in openjk rather then starting from zero with a jk2mv sp.

Jk2MV is only a thing because I didn't agree with some major decision the openjk made.
But it is completely irrelevant for SP.

It's not on our Todo list.
