### ISSUE TITLE
"MAX_SUBMODELS exceeded" when loading built-in map ns_streets

### ISSUE THREAD

**Issue by Gert-dev** [mvdevs/jk2mv#133]
When trying to change to the map `ns_streets` (Nar Shaddaa Streets) via console command `/map ns_streets`, the game bails with the error "MAX_SUBMODELS exceeded".

Other maps appear to work fine. There seems to be something about this map in particular.

**Comment by Daggolin** [comment]
The map `ns_streets` is a single player map and can't be loaded in multiplayer due to lower limits. The similary themed multiplayer map would be `ffa_ns_streets`.

As the limit is hardcoded in both, the server and the client, we can not increase it without adjusting a lot of other things, including the network protocol on both ends.
