### ISSUE TITLE
remove r_clear cheat protection 

### ISSUE THREAD

**Issue by WhiteMagicRaven** [mvdevs/jk2mv#153]
r_clear is just cvar that controls clear buffer filling

when turned of it can produce hall of mirrors

when enabled it fill empty space with certain color.

additional to that - please add r_clearColor cvar so with that cvar i can set black color, so hall of mirrors can be eliminated by that completely.

**Comment by aufau** [comment]
Again, do you have anything specific in mind? hall of mirror effect usually indicates a map bug and it's not something I see very often at all. Alternatively you can get it with noclip, but then cheats are enabled and you can set r_clear.

I appreciate these reports but if you report them as "feature requests" or "bug reports", as a regular player/user - please describe how do you think they would enhance the game exactly, with examples.

If you report them as a developer yourself because you've seen it in code or in ioq3 then it's another matter, but I understand this is not the case?

**Comment by WhiteMagicRaven** [comment]
its minor, i see it in bespin as spectator )
And i like when all that hall of mirrors is just filled with black color instead

**Comment by aufau** [comment]
done in https://github.com/mvdevs/jk2mv/commit/809284241eb5bca5eb6c974802425f72ca386e49
