### ISSUE TITLE
Demo playback broken on unix

### ISSUE THREAD

**Issue by comeroof** [mvdevs/jk2mv#2]
A demo recorded in a 1.02 server with JK2MV(b3) cannot be played. With original JK2 the demo recored with JK2MV works fine and can be played. The name of the demo reads "demo01.dm_15". The error message reads: "Error: Couldn't open demos/DEMO01.DM_15".

**Comment by ouned** [comment]
i guess it's a case sensitive problem, windows doesn't care, linux does. (together with https://github.com/mvdevs/jk2mv/issues/3 ) ?

**Comment by ouned** [comment]
ok i tested it, it's because jk2 writes the demo file called e.g. "demo0000.dm_15" and when you select it  in the menu you can already see it's uppercase.
Try playing your demo by typing in the console "demo demo0000", this should work.

I don't know if it's a good idea to make file system calls case insensitive on unix... q3 actually expects it like that but it's bad design somehow..

**Comment by comeroof** [comment]
Tested and works. Thanks.
