### ISSUE TITLE
Command completion on pressing enter

### ISSUE THREAD

**Issue by vvvjk2** [mvdevs/jk2mv#27]
For example, if you input
"cl_maxpa 100"
in the console and press ENTER, the command won't complete to cl_maxpackets even if it's the only thing it can complete to. It seems like it won't complete anything when an argument is supplied, which is contrary to basejk behavior.

So for the above to work as wanted, one must first write "cl_maxpa", press TAB so it completes to cl_maxpackets, and finally write the value. Is this intended? I remember seeing some bugs when I ported the ioquake3 command completion code to my own jk2 binary, but in the end I found some workarounds if you need inspiration. 

Oh, and I suggest removing the green color for the completion stuff - looks bad in my opinion. Either go with white or make some special color for it like grey. Maybe it's just me :smile:

**Comment by ouned** [comment]
but... I like the green :P

**Comment by ouned** [comment]
okey i just looked into it a bit and got frustrated about what a mess it is.
moved to 1.1 since it requires quiet a lot of changes

**Comment by ensiform** [comment]
How is it logical that cl_maxpa 100 would do anything?  You've typed a space, you've typed 100.  It should not complete the command argument.  Mind you `enter` completing the command at all is just weird anyway and not seen anywhere else but jk2 and jka WHILE in a server (not at main menu).

It was only added because that was their way of removing slash requirement while still retaining chat support in the console I would guess.

**Comment by ouned** [comment]
It isnt
Personally i dont care
But others complained

But
/disco and /qui gon jin is absolutely important :P

**Comment by ensiform** [comment]
Oh good lord. /q<tab><enter> is faster than typing out /qui gon jin
