### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by vvvjk2** [mvdevs/jk2mv#29]
- sv_minRate cvar (default 1000 or whatever is the hardcoded limit by default), can be set to for example 10000 so new players won't get a bad experience because they play with 20 snaps and 4000 rate (similarly, sv_minSnaps could be an idea for a new cvar. As could sv_maxSnaps, and it would be interesting to see how game feeling would change if snaps higher than 30 were allowed. But maybe that's taking it too far. )

- Tab completion for demo names (/demo <tab>, and it will bring a list of demos)

- this isn't strictly necessary, but I like the idea and I'm using it myself - tab completion for /model and /team_model commands

- The "savannah" bug seems to happen once in a while. I noticed it happen when a guy with "..." name connected, on  a server running mv 1.0rc2. The bug where people can't move / taunt for a short second when someone connects. I don't know exactly how this bug works, though.

- Linux: sound from jk2 continues playing when game is minimized. This can be fixed by checking value of the cvar "com_minimized" before playing sound a given frame (in function S_Update in snd_dma.cpp).

- Demo playback: when pressing any key, it brings up the ingame menu. While this is better than dropping to the main menu, it's still an annoyance. People should be free to press any key and have the game do the default action for that key. This is for allowing people to switch timescale during demo playback - e.g. bind j timescale 2, bind k timescale 0.5, etc.
Having the ingame menu brought up when pressing ESC is sufficient.
oh, and while we're at demo playback - I suggest removing cvar cheat protection during demo playback. In particular to allow for changing timescale value.

**Comment by ouned** [comment]
> The bug where people can't move / taunt for a short second when someone connects. I don't know exactly how this bug works, though.

that's most likely caused by the loading of the player model which the connecting player uses. The savannah bug normally causes the game to crash. (namecrash)
> Demo playback: when pressing any key, it brings up the ingame menu. While this is better than dropping to the main menu, it's still an annoyance.

yeah we are going to implement a lot of jomme features into 1.1. I'm even thinking of a menu for recording stuff with arrows to go forward and back in time etc.


for the rest: why don't you implement this stuff? If you are interested in this kind of "optimization", that's always welcome. I saw your modified command completion code but didn't want to spend to much time copying over stuff I don't understand. (I'm not really interested in this kind of stuff)
